// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using NamedQueryFiltersApp.Models;
using System;
using System.Collections.Generic;
using EntityFrameworkLibrary;
using Microsoft.Extensions.Logging;
using NamedQueryFiltersApp.Classes;

namespace NamedQueryFiltersApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(AppConnections.Instance.MainConnection,
            o => o.UseParameterizedCollectionMode(ParameterTranslationMode.Constant))
            //.EnableSensitiveDataLogging()
            .LogTo(new DbContextToFileLogger().Log, 
                [DbLoggerCategory.Database.Command.Name],
                LogLevel.Information); ;
    }

    /// <summary>
    /// Configures the model for the database context by defining entity configurations and query filters.
    /// </summary>
    /// <param name="modelBuilder">
    /// An instance of <see cref="ModelBuilder"/> used to configure the shape of entities, relationships, and database mappings.
    /// </param>
    /// <remarks>
    /// This method is overridden to apply specific configurations for the <see cref="Employee"/> entity, 
    /// such as property constraints and query filters. It also invokes the <c>OnModelCreatingPartial</c> method 
    /// to allow further customization in partial classes.
    /// </remarks>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
            
            entity.HasQueryFilter("SoftDelete", e => !e.IsDeleted);
            entity.HasQueryFilter("IsManager", e => e.IsManager);
            
        });

        OnModelCreatingPartial(modelBuilder);
    }

    /// <summary>
    /// Asynchronously saves all changes made in this context to the database.
    /// </summary>
    /// <param name="cancellationToken">
    /// A <see cref="CancellationToken"/> that can be used to cancel the asynchronous operation.
    /// </param>
    /// <returns>
    /// A task that represents the asynchronous save operation. The task result contains the number of state entries 
    /// written to the database.
    /// </returns>
    /// <remarks>
    /// This method overrides the base implementation to detect changes in the tracked entities and apply a soft delete 
    /// mechanism. Entities marked as deleted are instead updated with a flag indicating they are deleted, 
    /// without being physically removed from the database.
    /// </remarks>
    /// <exception cref="DbUpdateException">
    /// An error is encountered while saving to the database.
    /// </exception>
    /// <exception cref="OperationCanceledException">
    /// The operation is canceled if the provided <paramref name="cancellationToken"/> is triggered.
    /// </exception>
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ChangeTracker.DetectChanges();

        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.State == EntityState.Deleted)
            {
                // Change state to modified and set delete flag
                entry.State = EntityState.Modified;
                entry.Property("IsDeleted").CurrentValue = true;
            }
        }

        return await base.SaveChangesAsync(cancellationToken);
        
    }

    public override int SaveChanges()
    {
        
        ChangeTracker.DetectChanges();

        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.State == EntityState.Deleted)
            {
                // Change state to modified and set delete flag
                entry.State = EntityState.Modified;
                entry.Property("IsDeleted").CurrentValue = true;
            }
        }

        return base.SaveChanges();
        
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}