// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using EF_JsonHybridSample.Models;
using Microsoft.EntityFrameworkCore;

namespace EF_JsonHybridSample.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Applications> Applications { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(AppConnections.Instance.MainConnection);

    /// <summary>
    /// Configures the model for the database context by defining entity mappings, relationships, 
    /// and additional configurations.
    /// </summary>
    /// <param name="modelBuilder">
    /// An instance of <see cref="ModelBuilder"/> used to configure the shape of entities, 
    /// relationships between them, and database-specific configurations.
    /// </param>
    /// <remarks>
    /// This method is overridden to customize the EF Core model creation process. It includes:
    /// - Defining primary keys and required properties for the <see cref="Applications"/> entity.
    /// - Configuring owned types such as <see cref="MailSettings"/> and <see cref="GeneralSettings"/> 
    ///   to be stored as JSON.
    /// - Specifying column mappings for properties within owned types.
    /// - Ensuring required navigation properties for owned types.
    /// </remarks>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Applications>(entity =>
        {
            entity.HasKey(e => e.ApplicationId);
            entity.Property(e => e.ApplicationName)
                .IsRequired();
            entity.Property(e => e.ContactName)
                .IsRequired();

            entity.OwnsOne(e => e.MailSettings, mail =>
            {
                mail.ToJson();

                mail.Property(e => e.FromAddress)
                    .HasColumnName(nameof(MailSettings.FromAddress));

                mail.Property(e => e.Host)
                    .HasColumnName(nameof(MailSettings.Host));

                mail.Property(e => e.PickupFolder)
                    .HasColumnName(nameof(MailSettings.PickupFolder));

                mail.Property(e => e.Port)
                    .HasColumnName(nameof(MailSettings.Port));

                mail.Property(e => e.TimeOut)
                    .HasColumnName(nameof(MailSettings.TimeOut));
            });

            entity.OwnsOne(e => e.GeneralSettings, general =>
            {
                general.ToJson();

                general.Property(e => e.MainDatabaseConnection)
                    .HasColumnName(nameof(GeneralSettings.MainDatabaseConnection));

                general.Property(e => e.ServicePath)
                    .HasColumnName(nameof(GeneralSettings.ServicePath));
            });

            entity.Navigation(e => e.MailSettings)
                .IsRequired();

            entity.Navigation(e => e.GeneralSettings)
                .IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}