// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using UseIdentityColumnSample.Models;

namespace UseIdentityColumnSample.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    /// <summary>
    /// Configures the database context options, such as the database provider and connection string.
    /// </summary>
    /// <param name="optionsBuilder">
    /// An instance of <see cref="DbContextOptionsBuilder"/> used to configure the context.
    /// </param>
    /// <remarks>
    /// This method is called automatically by the framework when the context is being configured.
    /// It sets up the SQL Server provider using the connection string provided by <see cref="AppConnections.Instance.MainConnection"/>.
    /// </remarks>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(AppConnections.Instance.MainConnection);
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.Property(e => e.CustomerId).UseIdentityColumn(seed: 10, increment: 10);

            entity.Property(e => e.LastName).IsRequired();
            entity.Property(e => e.LastName).IsRequired();


        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}