// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ParameterizedCollectionModeSample.Classes;
using ParameterizedCollectionModeSample.Models;
using System;
using System.Collections.Generic;

namespace ParameterizedCollectionModeSample.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    /// <summary>
    /// Configures the database context options for the application.
    /// </summary>
    /// <param name="optionsBuilder">
    /// An instance of <see cref="DbContextOptionsBuilder"/> used to configure the database context.
    /// </param>
    /// <remarks>
    /// This method enables sensitive data logging (for demostration only), configures the SQL Server provider with a connection string, 
    /// and sets the parameterized collection mode to <see cref="ParameterTranslationMode.Constant"/>.
    /// Additionally, it logs database commands to a file using <see cref="DbContextToFileLogger"/>.
    /// </remarks>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .EnableSensitiveDataLogging()
            .UseSqlServer(AppConnections.Instance.MainConnection,
                o => o.UseParameterizedCollectionMode(ParameterTranslationMode.Constant))
            .LogTo(new DbContextToFileLogger().Log, new[]
                {
                    DbLoggerCategory.Database.Command.Name
                },
                LogLevel.Information);
    

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}