// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_JsonHybridSample.Models;

public partial class Applications
{
    public int ApplicationId { get; set; }

    public string ApplicationName { get; set; }

    public string ContactName { get; set; }

    public MailSettings MailSettings { get; set; } = new();

    public GeneralSettings GeneralSettings { get; set; } = new();
}