// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExecuteUpdateCodeSamples.Models;

public partial class Book
{
    public int Id { get; set; }

    public string BookName { get; set; }

    public decimal Price { get; set; }

    public int Rating { get; set; }
}